# Generated by Django 2.2.16 on 2022-04-12 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='Биография'),
            preserve_default=False,
        ),
    ]
