# Generated by Django 2.2.16 on 2022-04-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220413_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
